// Generates the overlay appearance chime and embeds it as C headers for
// the native overlays (windows/runner and linux/overlay). Run after any
// tweak to the sound design:
//
//   dart tool/generate_overlay_chime.dart
//
// Also writes build/overlay_chime.wav so the result can be auditioned.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

const sampleRate = 22050;
const durationMs = 180;

Int16List synthesizeChime() {
  // A calm two-tone blip (E5 + A5), fast attack, exponential decay. Peak
  // level stays low so the cue never startles in a quiet room.
  final sampleCount = (sampleRate * durationMs / 1000).round();
  final samples = Int16List(sampleCount);
  for (var i = 0; i < sampleCount; i++) {
    final t = i / sampleRate;
    final attack = math.min(1.0, t / 0.005);
    final decay = math.exp(-t / 0.045);
    final tone =
        0.8 * math.sin(2 * math.pi * 660 * t) +
        0.35 * math.sin(2 * math.pi * 880 * t);
    final value = 0.30 * attack * decay * tone;
    samples[i] = (value.clamp(-1.0, 1.0) * 32767).round();
  }
  return samples;
}

Uint8List buildWav(Int16List samples) {
  const bytesPerSample = 2;
  final dataLength = samples.length * bytesPerSample;
  final bytes = BytesBuilder();
  void writeString(String value) => bytes.add(value.codeUnits);
  void writeUint32(int value) => bytes.add(
    Uint8List(4)..buffer.asByteData().setUint32(0, value, Endian.little),
  );
  void writeUint16(int value) => bytes.add(
    Uint8List(2)..buffer.asByteData().setUint16(0, value, Endian.little),
  );

  writeString('RIFF');
  writeUint32(36 + dataLength);
  writeString('WAVE');
  writeString('fmt ');
  writeUint32(16);
  writeUint16(1); // PCM
  writeUint16(1); // mono
  writeUint32(sampleRate);
  writeUint32(sampleRate * bytesPerSample);
  writeUint16(bytesPerSample);
  writeUint16(16);
  writeString('data');
  writeUint32(dataLength);
  bytes.add(samples.buffer.asUint8List());
  return bytes.toBytes();
}

String buildHeader(Uint8List wav) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_overlay_chime.dart — do not edit.')
    ..writeln('// A soft two-tone cue played once when the overlay appears.')
    ..writeln('#ifndef TYPEMATE_OVERLAY_CHIME_WAV_H_')
    ..writeln('#define TYPEMATE_OVERLAY_CHIME_WAV_H_')
    ..writeln()
    ..writeln('static const unsigned int kOverlayChimeRate = $sampleRate;')
    ..writeln('static const unsigned int kOverlayChimeWavLen = ${wav.length};')
    ..writeln('static const unsigned char kOverlayChimeWav[] = {');
  for (var i = 0; i < wav.length; i += 12) {
    final chunk = wav
        .sublist(i, math.min(i + 12, wav.length))
        .map((b) => '0x${b.toRadixString(16).padLeft(2, '0')}')
        .join(', ');
    buffer.writeln('    $chunk,');
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('#endif  // TYPEMATE_OVERLAY_CHIME_WAV_H_');
  return buffer.toString();
}

String buildSwift(Uint8List wav) {
  final base64 = base64Encode(wav);
  return '''
// Generated by tool/generate_overlay_chime.dart — do not edit.
// A soft two-tone cue played once when the overlay appears; the same WAV
// is embedded in the Windows and Linux overlays.
let overlayChimeWavBase64 =
    "$base64"
''';
}

void main() {
  final wav = buildWav(synthesizeChime());
  final header = buildHeader(wav);
  File('windows/runner/overlay_chime_wav.h').writeAsStringSync(header);
  File('linux/overlay/overlay_chime_wav.h').writeAsStringSync(header);
  File('macos/Runner/OverlayChimeWav.swift').writeAsStringSync(buildSwift(wav));
  Directory('build').createSync(recursive: true);
  File('build/overlay_chime.wav').writeAsBytesSync(wav);
  stdout.writeln(
    'Wrote ${wav.length}-byte chime to windows/runner + linux/overlay '
    'headers and macos/Runner/OverlayChimeWav.swift, audition copy at '
    'build/overlay_chime.wav',
  );
}
