import 'dart:async';
import 'dart:ffi';
import 'dart:io';

import 'package:ffi/ffi.dart';
import 'package:flutter/services.dart' show rootBundle;

/// Plays the bundled dictation cues — the rising start chime when listening
/// begins and its falling inverse when a dictation fails — so both moments
/// are recognizable by ear alone. One Dart implementation for every
/// desktop: Windows through winmm's PlaySound (FFI), macOS through the
/// built-in afplay, Linux through paplay/aplay. No native runner code.
///
/// Both WAVs live in assets/sounds/, generated by
/// tool/generate_start_sound.dart and tool/generate_failure_tone.dart.
typedef DictationSoundPlayer = Future<void> Function();

const startSoundAssetPath = 'assets/sounds/dictation_start.wav';
const failureSoundAssetPath = 'assets/sounds/dictation_failed.wav';

Future<void> playDictationStartSound() =>
    _playBundledSound(startSoundAssetPath, 'typemate-dictation-start.wav');

Future<void> playDictationFailureSound() =>
    _playBundledSound(failureSoundAssetPath, 'typemate-dictation-failed.wav');

typedef _PlaySoundNative = Int32 Function(Pointer<Utf16>, IntPtr, Uint32);
typedef _PlaySoundDart = int Function(Pointer<Utf16>, int, int);

const _sndAsync = 0x0001;
const _sndNoDefault = 0x0002;
const _sndFilename = 0x00020000;

final _materializedPaths = <String, String>{};

// Allocated once per sound and kept: PlaySound(SND_ASYNC) may read the
// string after the call returns, so it must outlive playback.
final _utf16Paths = <String, Pointer<Utf16>>{};

Future<void> _playBundledSound(String assetPath, String tempName) async {
  // Unit-test runs must not beep on the developer's machine.
  if (Platform.environment['FLUTTER_TEST'] == 'true') {
    return;
  }
  try {
    final path = _materializedPaths[assetPath] ??= await _materialize(
      assetPath,
      tempName,
    );
    if (Platform.isWindows) {
      _playWindows(path);
    } else if (Platform.isMacOS) {
      unawaited(Process.run('afplay', [path]));
    } else if (Platform.isLinux) {
      unawaited(_playLinux(path));
    }
  } catch (_) {
    // Sound is a garnish; it must never break the dictation flow.
  }
}

/// The system players need a real file path, so the bundled asset is
/// written to the temp directory once per run.
Future<String> _materialize(String assetPath, String tempName) async {
  final data = await rootBundle.load(assetPath);
  final file = File(
    '${Directory.systemTemp.path}${Platform.pathSeparator}$tempName',
  );
  file.writeAsBytesSync(
    data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
    flush: true,
  );
  return file.path;
}

void _playWindows(String path) {
  final winmm = DynamicLibrary.open('winmm.dll');
  final playSound = winmm.lookupFunction<_PlaySoundNative, _PlaySoundDart>(
    'PlaySoundW',
  );
  final utf16 = _utf16Paths[path] ??= path.toNativeUtf16();
  playSound(utf16, 0, _sndFilename | _sndAsync | _sndNoDefault);
}

Future<void> _playLinux(String path) async {
  // PipeWire/Pulse desktops ship paplay; aplay covers bare ALSA setups.
  for (final command in [
    ['paplay', path],
    ['aplay', '-q', path],
  ]) {
    try {
      final result = await Process.run(command.first, command.sublist(1));
      if (result.exitCode == 0) {
        return;
      }
    } catch (_) {
      // Try the next player.
    }
  }
}
